experiment_name: linear_regression

seed: 42

model:
  type: Conv1DNet
  params:
    input_channels: 1
    output_channels: 1
    kernel_size: 3
    depth: 8
    width: 32
    activation: gelu # [ 'relu' , 'tanh' , 'gelu' , 'sigmoid' , 'leaky_relu' ]

training:
  epochs: 50
  batch_size: 128
  learning_rate: 3e-2
  loss_function: bce

data:
  type: torch
  path: data/train.pickle

eval:
  type: torch
  test_path: data/test.pickle
  metrics:
    - accuracy
    - f1_score
    - precision
    - recall
    - roc_auc
    - hamming_distance
    - bce
    - brier
    - ece

test:
  type: torch
  test_path: data/test.pickle
  output_file: data/test_predictions.pickle

runner: full_train