experiment_name: linear_regression

seed: 42

model:
  type: Linear_Regression
  params:
    L: 5

data:
  type: basic          # [ 'basic' , 'torch' ]
  path: data/train.pickle

eval:
  type: basic          # [ 'basic' , 'torch' ]
  test_path: data/test.pickle
  metrics:
    - accuracy
    - f1_score
    - precision
    - recall
    - roc_auc

test:
  type: basic
  test_path: data/test.pickle

runner: kfold